name: Schema Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'


jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "what is happening here?"
      - uses: tomhoule/grafbase-schema-check-action@main
