name: Schema Checks

on:
  workflow_dispatch:
  pull_request:

jobs:
  schema-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: tomhoule/grafbase-schema-check-action@main
        with:
          grafbase_access_token: TODO
          project_ref: tomhoule/grafbase-single-graph-ci-example@main
          schema_path: ./sdl.graphql
